#ifndef MATERIALCONVERTER_H
#define MATERIALCONVERTER_H

#include <QScopedPointer>
#include <QList>
#include <QByteArray>

#include "material.h"

namespace Troika {
    class VirtualFileSystem;
}
class ZipWriter;
class QString;
class MaterialConverterData;

/**
  Converts a single material from the ToEE MDF format to CgFx.
  Includes conversion and possible compression of the texture.
  */
class MaterialConverter
{
public:
    MaterialConverter(Troika::VirtualFileSystem *vfs);
    ~MaterialConverter();

    bool convert(const Troika::Material *material);

    /**
      Returns the textures to be embedded into the file enclosing the material.
      */
    const QList<QByteArray> &textures();

    /**
      Returns the material scripts generated by this converter.
      */
    const QList<QByteArray> &materialScripts();
private:
    QScopedPointer<MaterialConverterData> d_ptr;
};

#endif // MATERIALCONVERTER_H
